version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: gitsubmodule
  directory: /
  allow:
  - dependency-name: vcpkg
  - dependency-name: vendor/tactkeys
  schedule:
    interval: monthly
