read_globals = {
  'debug.getfunctionstats',
  'debug.getglobalstats',
  'debug.getstacktaint',
  'debug.gettaintmode',
  'debug.gettime',
  'debug.newsecurefunction',
  'debug.setnewclosuretaint',
  'debug.setprofilingenabled',
  'debug.setstacktaint',
  'debug.settaintmode',
  'forceinsecure',
  'hooksecurefunc',
  'issecure',
  'issecurevariable',
  'loadstring_untainted',
  'mod',
  'scrub',
  'securecall',
  'securecallfunction',
  'secureexecuterange',
  'seterrorhandler',
  'strcmputf8i',
  'strconcat',
  'strjoin',
  'strlenutf8',
  'strsplit',
  'strtrim',
  'table.removemulti',
  'table.wipe',
}
files['addon/Wowless'] = {
  read_globals = {
    'abs',
    'CreateFont',
    'CreateFrame',
    'debugprofilestop',
    'DevTools_Dump',
    'format',
    'RequestTimePlayed',
    'SendSystemMessage',
  },
}
exclude_files = {
  'meta.lua',
}
