describe('xml', function()
  local scripttypes = require('build.data.scripttypes')
  for _, p in ipairs(require('build.data.products')) do
    describe(p, function()
      local xml = require('build.data.products.' .. p .. '.xml')
      local uiobjects = require('build.data.products.' .. p .. '.uiobjects')
      local methods = {}
      local fields = {}
      local function flatten(k)
        if not methods[k] then
          local m, f = {}, {}
          for inh in pairs(uiobjects[k].inherits) do
            flatten(inh)
            for mk, mv in pairs(methods[inh]) do
              m[mk] = mv
            end
            for fk in pairs(fields[inh]) do
              f[fk] = true
            end
          end
          for mk, mv in pairs(uiobjects[k].methods) do
            m[mk] = mv.impl or true
          end
          for fk in pairs(uiobjects[k].fields) do
            f[fk] = true
          end
          methods[k] = m
          fields[k] = f
        end
      end
      for k in pairs(uiobjects) do
        flatten(k)
      end
      local usedscripts = {}
      for _, obj in pairs(uiobjects) do
        for name in pairs(obj.scripts or {}) do
          usedscripts[name] = true
        end
      end
      for name in pairs(usedscripts) do
        it(name .. ' is a ScriptType in xml', function()
          assert.equals('ScriptType', xml[name] and xml[name].extends)
        end)
      end
      for name, elem in pairs(xml) do
        describe(name, function()
          if elem.extends == 'ScriptType' then
            it('is in scripttypes', function()
              assert.Not.Nil(scripttypes[name])
            end)
          end
          -- Non-virtual xml tags that instantiate a uiobject type must only carry
          -- method/field attribute impls resolvable on that type, so attribute
          -- application never needs a does-this-method-exist check at runtime.
          if uiobjects[name] and not elem.virtual then
            local attrs = {}
            local e = elem
            while e do
              for an, a in pairs(e.attributes or {}) do
                attrs[an] = attrs[an] or a
              end
              e = e.extends and xml[e.extends] or nil
            end
            describe('attribute impls resolve', function()
              for an, a in pairs(attrs) do
                it(an, function()
                  local impl = type(a.impl) == 'table' and a.impl or nil
                  if impl and impl.method then
                    assert(methods[name][impl.method], ('%s.%s: no method %s'):format(name, an, impl.method))
                  elseif impl and impl.field then
                    assert(fields[name][impl.field], ('%s.%s: no field %s'):format(name, an, impl.field))
                  end
                end)
              end
            end)
            -- A method whose entire implementation is a generated trivial setter
            -- (self.field = value, no side effects) should be declared with a
            -- field impl instead, so attribute application skips the method
            -- call/lookup entirely.
            describe('method attribute impls are not trivial setters', function()
              for an, a in pairs(attrs) do
                it(an, function()
                  local impl = type(a.impl) == 'table' and a.impl or nil
                  if impl and impl.method then
                    local mimpl = methods[name][impl.method]
                    assert(
                      not (type(mimpl) == 'table' and mimpl.setter),
                      ('%s.%s: method %s is a trivial setter, use a field impl instead'):format(name, an, impl.method)
                    )
                  end
                end)
              end
            end)
            -- A method whose only implementation is the autogenerated no-op stub
            -- (no impl declared at all) can never do anything when driven by an
            -- attribute, so attribute method impls must resolve to a method that
            -- has a real implementation.
            describe('method attribute impls are not stubs', function()
              for an, a in pairs(attrs) do
                it(an, function()
                  local impl = type(a.impl) == 'table' and a.impl or nil
                  if impl and impl.method then
                    local mimpl = methods[name][impl.method]
                    assert(type(mimpl) == 'table', ('%s.%s: method %s is a stub'):format(name, an, impl.method))
                  end
                end)
              end
            end)
          end
        end)
      end
    end)
  end
end)
