describe('blp', function()
  it('reads', function()
    local w, h, rgb = require('wowless.blp').read('spec/wowless/temp.blp')
    assert.same(w, 64)
    assert.same(h, 64)
    require('wowless.png').write('temp.png', w, h, rgb)
  end)
end)
