describe('primtable', function()
  local newstate = require('wowless.ext').newstate
  local identity = [[local t = ...; return t]]

  describe('config', function()
    it('copies number', function()
      assert.same({ n = 1 }, newstate(identity, { n = 1 }))
    end)
    it('copies string', function()
      assert.same({ s = 'x' }, newstate(identity, { s = 'x' }))
    end)
    it('copies boolean true', function()
      assert.same({ b = true }, newstate(identity, { b = true }))
    end)
    it('copies boolean false', function()
      assert.same({ b = false }, newstate(identity, { b = false }))
    end)
    it('copies nested table', function()
      assert.same({ t = { a = 1 } }, newstate(identity, { t = { a = 1 } }))
    end)
    it('errors on function value', function()
      local ok, err = pcall(newstate, identity, { f = function() end })
      assert.False(ok)
      assert.truthy(err:find('function'))
    end)
    it('errors on thread value', function()
      local ok, err = pcall(newstate, identity, { t = coroutine.create(function() end) })
      assert.False(ok)
      assert.truthy(err:find('thread'))
    end)
    it('errors on userdata value', function()
      local ok, err = pcall(newstate, identity, { u = newproxy() })
      assert.False(ok)
      assert.truthy(err:find('userdata'))
    end)
    it('errors on nested unsupported value', function()
      local ok, err = pcall(newstate, identity, { t = { f = function() end } })
      assert.False(ok)
      assert.truthy(err:find('function'))
    end)
  end)

  describe('result', function()
    it('copies nil', function()
      assert.same(nil, newstate([[return nil]], {}))
    end)
    it('copies number', function()
      assert.same(42, newstate([[return 42]], {}))
    end)
    it('copies string', function()
      assert.same('hi', newstate([[return 'hi']], {}))
    end)
    it('copies boolean true', function()
      assert.same(true, newstate([[return true]], {}))
    end)
    it('copies boolean false', function()
      assert.same(false, newstate([[return false]], {}))
    end)
    it('copies table', function()
      assert.same({ a = 1, b = 'x' }, newstate([[return {a=1,b='x'}]], {}))
    end)
    it('errors on function result', function()
      local ok, err = pcall(newstate, [[return function() end]], {})
      assert.False(ok)
      assert.truthy(err:find('function'))
    end)
    it('errors on thread result', function()
      local ok, err = pcall(newstate, [[return coroutine.create(function() end)]], {})
      assert.False(ok)
      assert.truthy(err:find('thread'))
    end)
  end)
end)
