describe('sandbox', function()
  local m = require('wowless.sandbox')
  assert.same('table', type(m))
  assert.Nil(getmetatable(m))
  local s = m.create()
  assert.same('userdata', type(s))
  assert.same('wowless-sandbox', getmetatable(s))

  describe('dostring', function()
    it('requires a string', function()
      assert.errors(function()
        s:dostring()
      end)
    end)
    it('requires valid lua', function()
      assert.errors(function()
        s:dostring('"boo"')
      end)
    end)
    it('works', function()
      assert.same({ 42, nil, 'moo', true }, { s:dostring('return 42, {}, "moo", true') })
    end)
    it('works with asserts', function()
      assert.same(true, pcall(s.dostring, s, 'assert(true)'))
    end)
    it('propagates errors', function()
      assert.same(false, pcall(s.dostring, s, 'assert(false)'))
    end)
    it('has _VERSION', function()
      assert.same('Lua 5.1', s:dostring('return _VERSION'))
    end)
  end)
end)
