describe('sandbox', function()
  local lib = require('wowless.sandbox')
  it('does not crash', function()
    local sandbox = lib.create()
    assert.same(0, sandbox:eval('function foo(x) return 42 + x end'))
    assert.same(0, sandbox:eval('foo(0)'))
    assert.same(0, sandbox:eval('foo(99)'))
  end)
end)
