describe('sandbox', function()
  local lib = require('wowless.sandbox')
  it('does not crash', function()
    local sandbox = lib.create()
    assert.same({ 42 }, { sandbox:eval('return 42') })
    assert.same({ 1, '2', 3 }, { sandbox:eval('return 1, "2", 3') })
    assert.same({ nil }, { sandbox:eval('return nil') })
    assert.same({ true }, { sandbox:eval('return true') })
    assert.errors(function()
      sandbox:eval('return {}')
    end)
    assert.errors(function()
      sandbox:eval('return function() end')
    end)
    assert.errors(function()
      sandbox:eval('return newproxy()')
    end)
  end)
end)
