describe('loader', function()
  local loader = require('wowless.loader')
  it('loads', function()
    local api = loader.run(0)
    assert.same(0, api.errors)
    api:SendEvent('PLAYER_LOGIN')
    assert.same(0, api.errors)
    api:SendEvent('PLAYER_ENTERING_WORLD')
    assert.same(0, api.errors)
  end)
end)
