describe('runner', function()
  local runner = require('wowless.runner')
  it('loads wow classic', function()
    local api = runner.run(0, 'extracts/wow_classic/Interface', 'TBC')
    assert.same(0, api.GetErrorCount())
  end)
  it('loads wow classic era', function()
    local api = runner.run(0, 'extracts/wow_classic_era/Interface', 'Vanilla')
    assert.same(0, api.GetErrorCount())
  end)
end)
