describe('runner', function()
  local runner = require('wowless.runner')
  it('loads wow classic', function()
    local api = runner.run(0, 'wow_classic')
    assert.same(1, api.GetErrorCount())
  end)
  it('loads wow classic era', function()
    local api = runner.run(0, 'wow_classic_era')
    assert.same(1, api.GetErrorCount())
  end)
end)
