describe('util #small', function()
  local util = require('wowless.util')
  describe('strjoin', function()
    it('returns empty with no elements', function()
      assert.same('', util.strjoin('foo'))
    end)
    it('returns just the element when only one', function()
      assert.same('bar', util.strjoin('foo', 'bar'))
    end)
    it('joins', function()
      assert.same('barfoobazfooquux', util.strjoin('foo', 'bar', 'baz', 'quux'))
    end)
  end)
  describe('strtrim', function()
    it('does nothing when nothing to trim', function()
      assert.same('foo', util.strtrim('foo'))
    end)
    it('trims', function()
      assert.same('foo', util.strtrim(' foo '))
    end)
  end)
end)
