describe('yaml', function()
  local yaml = require('wowapi.yaml')
  describe('parse', function()
    it('works on empty', function()
      assert.Nil(yaml.parse(''))
    end)
  end)
  describe('pprint', function()
    it('works on empty', function()
      assert.same('--- {}\n', yaml.pprint({}))
    end)
  end)
end)
