local indir, outdir = unpack(arg)
local lfs = require('lfs')
local pf = require('pl.file')
local yaml = require('wowapi.yaml')
local tags = {
  'wow',
  'wowt',
  'wow_classic',
  'wow_classic_era',
  'wow_classic_era_ptr',
  'wow_classic_ptr',
}
local docs = {}
local enum = {}
for _, tag in ipairs(tags) do
  local tagdir = indir .. '/' .. tag
  local docdir = tagdir .. '/Interface/AddOns/Blizzard_APIDocumentation'
  for f in lfs.dir(docdir) do
    if f:sub(-4) == '.lua' then
      pcall(setfenv(loadfile(docdir .. '/' .. f), {
        APIDocumentation = {
          AddDocumentationTable = function(_, t)
            docs[f] = docs[f] or {}
            docs[f][tag] = t
          end,
        }
      }))
    end
  end
  local env = {}
  setfenv(loadfile(tagdir .. '/Interface/GlobalEnvironment.lua'), env)()
  for en in pairs(env.Enum) do
    enum[en] = true
  end
end
lfs.mkdir(outdir)
local types = {
  bool = 'b',
  number = 'n',
  string = 's',
  table = 't',
}
local tables = {
  Constants = 'n',
  Enumeration = 'n',
  Structure = 't',
}
local tys = {}
-- First pass for types.
for _, envt in pairs(docs) do
  for _, t in pairs(envt) do
    for _, ty in ipairs(t.Tables or {}) do
      local c = assert(tables[ty.Type])
      local old = tys[ty.Name]
      if old then
        assert(old == c)
      else
        tys[ty.Name] = c
      end
    end
  end
end
local function insig(fn)
  local inputs = ''
  local firstDefault = nil
  for i, a in ipairs(fn.Arguments or {}) do
    local c = types[a.Type] or tys[a.Type] or (enum[a.Type] and 'n')
    if not c then
      print('unknown type ' .. a.Type)
      c = '?'
    end
    firstDefault = firstDefault or ((a.Default or a.Nilable) and i)
    inputs = inputs .. c
  end
  local t = {}
  if firstDefault then
    for i = firstDefault, inputs:len() do
      table.insert(t, inputs:sub(1, i-1))
    end
  end
  table.insert(t, inputs)
  return t
end
local function outsig(fn)
  local outputs = ''
  for _, r in ipairs(fn.Returns or {}) do
    local c = (r.Nilable and 'x') or types[r.Type] or tys[r.Type] or (enum[r.Type] and 'n')
    if not c then
      print('unknown type ' .. r.Type)
      c = '?'
    end
    outputs = outputs .. c
  end
  return outputs
end
local functions = {}
for f, envt in pairs(docs) do
  for env, t in pairs(envt) do
    if t.Name then
      assert(t.Type == 'System', f)
      for _, fn in ipairs(t.Functions or {}) do
        assert(fn.Type == 'Function', f)
        local name = (t.Namespace and (t.Namespace .. '.') or '') .. fn.Name
        functions[name] = functions[name] or {}
        functions[name][env] = fn
      end
    end
  end
end
local doNotAutogen = {}
for f in lfs.dir(outdir) do
  if f:sub(-5) == '.yaml' then
    local fn = f:sub(1, -6)
    local api = yaml.parseFile(outdir .. '/' .. f)
    if api.status ~= 'autogenerated' then
      doNotAutogen[fn] = true
    end
  end
end
for name, envfn in pairs(functions) do
  if not doNotAutogen[name] then
    local inputs = {}
    local outputs = nil
    for _, fn in pairs(envfn) do
      for _, input in ipairs(insig(fn)) do
        inputs[input] = true
      end
      outputs = outputs or outsig(fn)
    end
    local inlist = {}
    for input in pairs(inputs) do
      table.insert(inlist, input)
    end
    table.sort(inlist)
    pf.write(outdir .. '/' .. name .. '.yaml', yaml.pprint({
      name = name,
      status = 'autogenerated',
      inputs = #inlist == 1 and inlist[1] or inlist,
      outputs = outputs,
    }))
  end
end
