local args = (function()
  local parser = require('argparse')()
  parser:argument('input', 'input file')
  parser:option('-c --cascproxy', 'cascproxy for textures')
  parser:option('-o --output', 'output file')
  return parser:parse()
end)()
local t = require('wowapi.yaml').parseFile(args.input)
local out = args.output or require('pl.path').splitext(args.input) .. '.png'
require('wowless.render').rects2png(t, args.cascproxy, out)
