include(CheckCCompilerFlag)
check_c_compiler_flag(-ffast-math HAVE_FFAST_MATH)
check_c_compiler_flag(/fp:fast HAVE_FP_FAST)
if(HAVE_FFAST_MATH)
  add_compile_options(-ffast-math)
elseif(HAVE_FP_FAST)
  add_compile_options(/fp:fast)
else()
  message(FATAL_ERROR "No fast-math flag available; required for correctness")
endif()
