file(READ "${SRC}" content)
string(FIND "${content}" "__LINE__" pos)
while(NOT pos EQUAL -1)
  string(SUBSTRING "${content}" 0 ${pos} before)
  string(LENGTH "${before}" before_len)
  string(REPLACE "\n" "" no_newlines "${before}")
  string(LENGTH "${no_newlines}" no_newlines_len)
  math(EXPR line_num "${before_len} - ${no_newlines_len} + 1")
  math(EXPR after "${pos} + 8")
  string(SUBSTRING "${content}" ${after} -1 rest)
  set(content "${before}${line_num}${rest}")
  string(LENGTH "${before}${line_num}" search_start)
  string(SUBSTRING "${content}" ${search_start} -1 tail)
  string(FIND "${tail}" "__LINE__" next_pos)
  if(next_pos EQUAL -1)
    break()
  endif()
  math(EXPR pos "${search_start} + ${next_pos}")
endwhile()
file(WRITE "${DST}" "${content}")
