name: pre-commit autoupdate
on:
  schedule:
  - cron: 0 0 1 * *
  workflow_dispatch:
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v7
    - run: pipx run pre-commit autoupdate
    - uses: peter-evans/create-pull-request@v8
      with:
        branch: update/pre-commit-hooks
        commit-message: pre-commit autoupdate
        title: pre-commit autoupdate
        token: ${{ secrets.PRE_COMMIT_AUTOUPDATE_TOKEN }}
